### ISSUE TITLE
Not working with Enterprise?

### ISSUE THREAD

**Issue by kzssc** [rhydlewis/search-omnifocus#49]
Hi there, I've recently installed the Omnifocus Enterprise (one from Appstore, not from Omnifocus) and it the plug-in doesn't appear to be able to pull content from the database. Kindly ask for your help looking into the matter, please! Cheers! 
Screenshot attached here. 
https://transfer.sh/1sZBMLW/Screenshot%202021-07-31%20at%2017.31.04.png

**Comment by kzssc** [comment]
I checked the post on alfredforum and figured that my problem might be to do with directory... I paste the debug info here: 

[17:41:35.784] Search OmniFocus[Script Filter] Queuing argument 't'
[17:41:36.000] Search OmniFocus[Script Filter] Script with argv '(null)' finished
[17:41:36.003] ERROR: Search OmniFocus[Script Filter] Code 1: .
17:41:35 workflow.py:2061 DEBUG    ---------- Search OmniFocus (2.1.3) ----------
17:41:35 workflow.py:1468 DEBUG    reading settings from /Users/vpchris/Library/Application Support/Alfred/Workflow Data/net.rhydlewis.alfred.searchomnifocus/settings.json
17:41:35 workflow.py:2343 DEBUG    update check not due
17:41:35 search.py:45 DEBUG    Started workflow
17:41:35 search.py:162 DEBUG    [u't']
17:41:35 workflow.py:1695 DEBUG    loading cached data: /Users/vpchris/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.rhydlewis.alfred.searchomnifocus/__workflow_latest_version.cpickle
17:41:35 search.py:176 DEBUG    Using stored icon_root:'/Applications/OmniFocus.localized/OmniFocus.app/Contents/Resources'
17:41:35 search.py:142 DEBUG    Searching tasks
17:41:35 search.py:64 DEBUG    SELECT t.persistentIdentifier AS id, t.name AS name, t.dateCompleted as date_completed, t.blockedByFutureStartDate AS blocked_by_future_start_date, p.name AS project_name, t.flagged, t.dateToStart AS start_date, t.inInbox AS in_inbox, t.effectiveInInbox AS effective_in_inbox, t.effectiveDateToStart AS effective_start_date, t.childrenCountAvailable AS child_count, t.blocked AS blocked, pi.status AS status, t.effectiveFlagged, t.dateModified AS modified, t.containingProjectInfo AS parent, t.dateDue AS due_date, t.effectiveContainingProjectInfoRemaining AS project_remaining FROM ((task tt left join projectinfo pi on tt.containingprojectinfo=pi.pk) t left join task p on t.task=p.persistentIdentifier)  WHERE (t.effectiveInInbox = 0 AND t.inInbox = 0) AND t.dateCompleted IS NULL AND lower(t.name) LIKE lower('%t%') AND (t.containingProjectInfo <> t.persistentIdentifier OR t.containingProjectInfo is NULL)  ORDER BY t.name ASC
17:41:35 search.py:187 DEBUG    OmniFocus db not found at /Users/vpchris/Library/Group Containers/34YW5XSRB7.com.omnigroup.OmniFocus/com.omnigroup.OmniFocus3/com.omnigroup.OmniFocusModel/OmniFocusDatabase.db; using /Users/vpchris/Library/Group Containers/34YW5XSRB7.com.omnigroup.OmniFocus/com.omnigroup.OmniFocus3.MacAppStore/com.omnigroup.OmniFocusModel/OmniFocusDatabase.db instead
17:41:35 search.py:197 DEBUG    /Users/vpchris/Library/Group Containers/34YW5XSRB7.com.omnigroup.OmniFocus/com.omnigroup.OmniFocus3.MacAppStore/com.omnigroup.OmniFocusModel/OmniFocusDatabase.db
17:41:35 workflow.py:2080 ERROR    unable to open database file
Traceback (most recent call last):
  File "/Users/vpchris/SynologyDrive/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.F7C2D3A6-3EC1-49B8-B4F1-59A3D762281F/workflow/workflow.py", line 2073, in run
    func(self)
  File "search.py", line 56, in main
    get_results(sql, args.type, factory)
  File "search.py", line 65, in get_results
    results = run_query(sql)
  File "search.py", line 209, in run_query
    conn = sqlite3.connect(db_path)
OperationalError: unable to open database file
17:41:35 workflow.py:2103 DEBUG    ---------- finished in 0.022s ----------
[17:41:36.007] Search OmniFocus[Script Filter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Error in workflow 'Search OmniFocus'</title><subtitle>unable to open database file</subtitle><icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns</icon></item></items>

**Comment by rhydlewis** [comment]
Weird. The workflow can't find your OmniFocus database at the expected location. I don't have access to OmniFocus Enterprise but assuming that it has a different location compared to the regular Mac AppStore app. Can you run this from Terminal.app and share the result?

`cd ~/Library/Group\ Containers/`
`find . -name "OmniFocus*.db"`

**Comment by kzssc** [comment]
./34YW5XSRB7.com.omnigroup.OmniFocus/com.omnigroup.OmniFocus3.enterprise/com.omnigroup.OmniFocusModel/OmniFocusDatabase.db
find: ./group.com.apple.notes: Operation not permitted

Cheers!

**Comment by csss1234** [comment]
Im having the same problem, and gettings the exact same printout as @kzssc
